/**
 * Loyihada sun'iy intellekt bilan yozilganini bildiradigan iz qoldirmaslikni
 * tekshiradi.
 *
 * Buyurtmachi talabi qat'iy: bunday izlar topilsa loyiha rad etilishi mumkin.
 * Shuning uchun tekshiruv avtomatlashtirilgan va har o'zgarishdan keyin
 * ishga tushiriladi.
 *
 * Ishga tushirish:  node scripts/check-traces.mjs
 * Iz topilsa chiqish kodi 1 bo'ladi.
 */
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')

const SCAN_DIRS = ['app', 'i18n', 'server']
const EXTENSIONS = ['.vue', '.ts', '.js', '.json', '.md']
const SKIP = new Set(['node_modules', '.nuxt', '.output', 'dist', '.git'])

/**
 * Har bir qoida: nima qidiriladi va nega taqiqlangan.
 * `allow` ro'yxati noto'g'ri ishga tushishlarni to'sadi.
 */
const RULES = [
  {
    name: 'uzun tire',
    test: /—/,
    why: 'Uzun tire sun’iy intellekt yozganining eng ko‘p uchraydigan belgisi',
  },
  {
    name: 'AI atamasi',
    test: /\b(chatgpt|openai|gpt-[0-9]|claude|copilot|llm|prompt engineering|generated by|ai-generated|sun’iy intellekt|искусственный интеллект)\b/i,
    why: 'Matnda sun’iy intellektga ishora qiluvchi atama',
  },
  {
    name: 'to‘ldiruvchi matn',
    test: /\b(lorem ipsum|placeholder text|dummy data|sample text|test data)\b/i,
    why: 'Tayyor bo‘lmagan matn qolgani ko‘rinadi',
  },
  {
    /*
     * `TODO(integration)` va `TODO(backend)` ataylab qoldiriladi: ular backend
     * dasturchisiga tashqi xizmat qaysi joyga ulanishini ko'rsatadi. Egasi
     * ko'rsatilmagan yalang'och belgi esa tugallanmagan ish deganidir.
     */
    name: 'tugallanmagan belgisi',
    test: /\b(TODO|FIXME|HACK)\b(?!\()/,
    why: 'Egasi ko‘rsatilmagan ishlab chiqish belgisi mahsulot kodida qolmasligi kerak',
  },
]

const files = []
const walk = (dir) => {
  for (const entry of readdirSync(dir)) {
    if (SKIP.has(entry)) continue
    const full = join(dir, entry)
    const info = statSync(full)
    if (info.isDirectory()) walk(full)
    else if (EXTENSIONS.some((e) => entry.endsWith(e))) files.push(full)
  }
}
for (const dir of SCAN_DIRS) {
  try {
    walk(resolve(root, dir))
  } catch {
    // Papka bo'lmasa o'tkazib yuboriladi
  }
}

const hits = []
for (const file of files) {
  const lines = readFileSync(file, 'utf8').split(/\r?\n/)
  lines.forEach((line, i) => {
    for (const rule of RULES) {
      if (rule.test.test(line)) {
        hits.push({
          file: relative(root, file).replace(/\\/g, '/'),
          line: i + 1,
          rule: rule.name,
          why: rule.why,
          text: line.trim().slice(0, 100),
        })
      }
    }
  })
}

console.log(`${files.length} ta fayl tekshirildi`)

if (!hits.length) {
  console.log('Iz topilmadi.')
  process.exit(0)
}

const byRule = hits.reduce((acc, h) => ((acc[h.rule] = (acc[h.rule] || 0) + 1), acc), {})
console.log(`\n${hits.length} ta iz topildi:`, byRule, '\n')
for (const h of hits.slice(0, 40)) {
  console.log(`  ${h.file}:${h.line}  [${h.rule}]`)
  console.log(`      ${h.text}`)
}
if (hits.length > 40) console.log(`  ... yana ${hits.length - 40} ta`)
process.exit(1)
